### ISSUE TITLE
Getting started question

### ISSUE THREAD

**Issue by peterjduffy** [simonknittel/obsidian-create-task#24]
![Screenshot 2024-07-23 at 04 46 06](https://github.com/user-attachments/assets/81429e60-1dde-4e7e-a7c3-7509788f43a0)
im probably being stupid but how do I create the note path for the default note?  I keep getting a message it doesn't like my filepath. Thanks!

**Comment by simonknittel** [comment]
Hi! There are no stupid questions 🙂

You have to include the file extension in the path. In your case this would be `2. Area/Tasks.md`

**Comment by peterjduffy** [comment]
Thank you!On 23 Jul 2024, at 06:20, Simon Knittel ***@***.***> wrote:﻿
Hi! There are no stupid questions 🙂
You have to include the file extension in the path. Im your case this would be 2. Area/Tasks.md
